######################################################################################
# docker-compose[ubuntu]
#
######################################################################################
version: '2'
services:

  redmine:
    # ビルドイメージ
    build: ./build
    # タグ名
    image: develop/ubuntu:16.04
    # コンテナ名
    container_name: ubuntu
    # 環境変数
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.UTF-8
      - L C_ALL ja_JP.UTF-8
      - LC_CTYPE ja_JP.UTF-8
